title: "Raif Turner Portfolio"
description: "Sharing my ideas, explorations, and side projects"
author: "Raiford Turner"
email: "raifordturner@gmail.com"
baseurl: "" # Leave blank for your root domain
url: "https://raifordturner.github.io" # Replace with your GitHub Pages URL
theme: "jekyll-theme-cayman" # Or use a custom theme
markdown: kramdown
